In [1]:
import numpy as np

In [2]:
streetlights = np.array([
                    [1, 0, 1],
                    [0, 1, 1],
                    [0, 0, 1],
                    [1, 1, 1],
                    [0, 1, 1],
                    [1, 0, 1]
                            ])

walk_vs_stop = np.array([[0],
                         [1],
                         [0],
                         [1],
                         [1],
                         [0]
    
                            ]).reshape(-1)

weights = np.array([0.5, 0.48, -0.7])
lr = 0.1

for iteration in range(1):
    error_all = 0
    for i in range(len(walk_vs_stop)):
        prediction = streetlights[i].dot(weights.reshape(-1, 1))
        error = (prediction - walk_vs_stop[i]) ** 2
        print(prediction)
        error_all += error
        delta = prediction - walk_vs_stop[i]
#         weights -= lr * (streetlights[i] * delta)
    
#     if iteration % 10 == 0:
#         print(f'Error: \n{error.sum() / len(weights)} \nPrediction: \n{prediction}')
    print(error_all)

[-0.2]
[-0.22]
[-0.7]
[0.28]
[-0.22]
[-0.2]
[4.0652]


In [3]:
streetlights = np.array([
                    [1, 0, 1],
                    [0, 1, 1],
                    [0, 0, 1],
                    [1, 1, 1],
                    [0, 1, 1],
                    [1, 0, 1]
                            ])

walk_vs_stop = np.array([[0],
                         [1],
                         [0],
                         [1],
                         [1],
                         [0]
    
                            ]).reshape(-1)

weights = np.array([0.5, 0.48, -0.7])
lr = 0.1

for iteration in range(50):
    error_all = 0
    prediction = streetlights.dot(weights)
    error = ((prediction - walk_vs_stop) ** 2).sum()
    delta = prediction - walk_vs_stop
    weights_delta = delta.dot(streetlights)
    weights -= lr * weights_delta

    if iteration % 10 == 0:
        print(prediction)
        print(error)

[-0.2  -0.22 -0.7   0.28 -0.22 -0.2 ]
4.0652
[ 0.04028363  0.93076197 -0.13549065  1.10653625  0.93076197  0.04028363]
0.042541041870533404
[-0.00158342  0.98665678 -0.06984847  1.05492183  0.98665678 -0.00158342]
0.008256313792683748
[-0.00321616  0.99552114 -0.03600845  1.02831344  0.99552114 -0.00321616]
0.002159067174885018
[-0.00191569  0.99794873 -0.01856317  1.01459621  0.99794873 -0.00191569]
0.0005733956608956122


In [4]:
weights

array([ 0.00855448,  1.00853992, -0.00956973])

## Глубокая нейронная сеть

In [17]:
import numpy as np

In [20]:
np.random.seed(1)

def relu(x):
    return (x > 0) * x

def relu2deriv(output):
    return output > 0

lr = 0.2
hidden_size = 4

streetlights = np.array([
                    [1, 0, 1],
                    [0, 1, 1],
                    [0, 0, 1],
                    [1, 1, 1]
                            ])

walk_vs_stop = np.array([[1, 1, 0, 0]]).T

weights_0_1 = 2 * np.random.random((3, hidden_size)) - 1
weights_1_2  = 2 * np.random.random((hidden_size, 1)) - 1

for iteration in range(60):
    layer_2_error = 0
    for i in range(streetlights.shape[0]):
        layer_0 = streetlights[i].reshape(1, -1)
        layer_1 = relu(layer_0.dot(weights_0_1))
        layer_2 = layer_1.dot(weights_1_2)

        layer_2_error += ((layer_2 - walk_vs_stop[i].reshape(1, -1))**2).sum()
        
        layer_2_delta = (walk_vs_stop[i].reshape(1, -1) - layer_2)
        layer_1_delta = layer_2_delta.dot(weights_1_2.T) * relu2deriv(layer_1)
        
        weights_1_2 += lr * layer_1.T.dot(layer_2_delta)
        weights_0_1 += lr * layer_0.T.dot(layer_1_delta)
#         break
    if iteration % 10 == 9:
        print(f'Error: {layer_2_error}')

Error: 0.6342311598444467
Error: 0.35838407676317513
Error: 0.0830183113303298
Error: 0.006467054957103705
Error: 0.0003292669000750734
Error: 1.5055622665134859e-05


## Воспроизведение трехслойной нейронной сети по памяти

In [75]:
import numpy as np
np.random.seed(1)

def relu(x):
    return (x > 0) * x

def relu2deriv(output):
    return output > 0

lr = 0.2
hidden_size = 4

streetlights = np.array([
                    [1, 0, 1],
                    [0, 1, 1],
                    [0, 0, 1],
                    [1, 1, 1]
                            ])

walk_vs_stop = np.array([[1, 1, 0, 0]]).T

weights_0_1 = 2 * np.random.random((3, hidden_size)) - 1
weights_1_2 = 2 * np.random.random((hidden_size, 1)) - 1

for iteration in range(60):
    layer_2_error = 0
    for i in range(streetlights.shape[0]):
        layer_0 = streetlights[i].reshape(1, -1)
        layer_1 = relu(layer_0.dot(weights_0_1))
        layer_2 = layer_1.dot(weights_1_2)
        layer_2_error += ((layer_2 - walk_vs_stop[i].reshape(1, -1)) ** 2).sum()
        
        layer_2_delta = layer_2 - walk_vs_stop[i].reshape(1, -1)
        layer_1_delta = layer_2_delta.dot(weights_1_2.T) * relu2deriv(layer_1)
        
        weights_1_2 -= lr * (layer_1.T * layer_2_delta)
        weights_0_1 -= lr * (layer_0.T * layer_1_delta)
#         break
    if iteration % 10 == 9:
        print(f'Error: {layer_2_error}')

Error: 0.6342311598444467
Error: 0.35838407676317513
Error: 0.0830183113303298
Error: 0.006467054957103705
Error: 0.0003292669000750734
Error: 1.5055622665134859e-05


In [76]:
weights_0_1

array([[-0.16595599,  0.91056768, -0.99977125, -0.90023925],
       [-0.70648822, -0.92794391, -0.62747958,  0.89703458],
       [-0.20646505, -0.03308324, -0.16161097,  0.00237016]])

In [77]:
weights_1_2

array([[-0.5910955 ],
       [ 1.13962134],
       [-0.94522481],
       [ 1.11023793]])