In [1]:
import numpy as np

In [128]:
streetlights = np.array([
                    [1, 0, 1],
                    [0, 1, 1],
                    [0, 0, 1],
                    [1, 1, 1],
                    [0, 1, 1],
                    [1, 0, 1]
                            ])

walk_vs_stop = np.array([[0],
                         [1],
                         [0],
                         [1],
                         [1],
                         [0]
    
                            ]).reshape(-1)

weights = np.array([0.5, 0.48, -0.7])
lr = 0.1

for iteration in range(1):
    error_all = 0
    for i in range(len(walk_vs_stop)):
        prediction = streetlights[i].dot(weights.reshape(-1, 1))
        error = (prediction - walk_vs_stop[i]) ** 2
        print(prediction)
        error_all += error
        delta = prediction - walk_vs_stop[i]
#         weights -= lr * (streetlights[i] * delta)
    
#     if iteration % 10 == 0:
#         print(f'Error: \n{error.sum() / len(weights)} \nPrediction: \n{prediction}')
    print(error_all)

[-0.2]
[-0.22]
[-0.7]
[0.28]
[-0.22]
[-0.2]
[4.0652]


In [151]:
streetlights = np.array([
                    [1, 0, 1],
                    [0, 1, 1],
                    [0, 0, 1],
                    [1, 1, 1],
                    [0, 1, 1],
                    [1, 0, 1]
                            ])

walk_vs_stop = np.array([[0],
                         [1],
                         [0],
                         [1],
                         [1],
                         [0]
    
                            ]).reshape(-1)

weights = np.array([0.5, 0.48, -0.7])
lr = 0.1

for iteration in range(50):
    error_all = 0
    prediction = streetlights.dot(weights)
    error = ((prediction - walk_vs_stop) ** 2).sum()
    delta = prediction - walk_vs_stop
    weights_delta = delta.dot(streetlights)
    weights -= lr * weights_delta

    if iteration % 10 == 0:
        print(prediction)
        print(error)

[-0.2  -0.22 -0.7   0.28 -0.22 -0.2 ]
4.0652
[ 0.04028363  0.93076197 -0.13549065  1.10653625  0.93076197  0.04028363]
0.042541041870533404
[-0.00158342  0.98665678 -0.06984847  1.05492183  0.98665678 -0.00158342]
0.008256313792683748
[-0.00321616  0.99552114 -0.03600845  1.02831344  0.99552114 -0.00321616]
0.002159067174885018
[-0.00191569  0.99794873 -0.01856317  1.01459621  0.99794873 -0.00191569]
0.0005733956608956122


In [ ]:
149